name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  dummy-release:
    name: Create a dummy release
    runs-on: ubuntu-latest
    steps:
      - name: Create a new release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{github.run_number}}
          name: Release v${{github.run_number}}
