name: Deploy to production

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

env:
  RELEASE: ${{ format('v{0}', github.event.workflow_run.run_number) }}
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: production
    environment: prod
    permissions:
      deployments: write
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'}}

    steps:
      - name: Create deployment
        id: create_deployment
        uses: avakar/create-deployment@8711a60d47672e4d77a3d1298802410a9edc877e
        with:
          environment: prod
          production_environment: true
          description: Deployment of release ${{ env.RELEASE }} to prod
          ref: ${{ env.RELEASE }}
          payload: '{ "run_id": "${{ github.run_id }}" }'
          auto_merge: false

      - name: Update deployment status
        uses: avakar/set-deployment-status@578b982d2ad5f56e50864f9e21ec354a073cd6f5
        if: always()
        with:
          deployment_id: ${{ steps.create_deployment.outputs.deployment_id }}
          state: ${{ job.status == 'success' && 'success' || 'failure' }}
